spring:
  application:
    name: guestbook
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://np.eeerrorcode.com:3306/guestbook
    username: guestbook
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      - src/main/resources
      - templates